/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:9d3a5a9b-e0f5-4403-b5cf-15ad4ee98b3f",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Vbrwyyg5p",
    "aws_user_pools_web_client_id": "5c11b37ofb1ok2518rf90mi10b",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://eatuofvjozb4dpm65rblaqx5wy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-c6nbujitzjej7gtvfzuchlamey"
};


export default awsmobile;
